const gamesData = [
  {
    id: "flappy-rocket",
    title: "Flappy Rocket",
    category: "Arcade",
    description: "Navigate your cosmic rocket ship through dangerous orbital barriers. Tap or click to thrust upward!",
    mechanics: "One-button control to adjust altitude.",
    difficulty: "Medium",
    rating: 4.8,
    playable: true,
    color: "var(--neon-pink)",
    icon: "🚀",
    accent: "#ff007f"
  },
  {
    id: "stack-tower",
    title: "Stack Tower Builder",
    category: "Casual",
    description: "Align sliding slabs precisely to build the tallest skyscraper in the galaxy. Overhangs will be sliced off!",
    mechanics: "Tap/Click to drop the blocks precisely.",
    difficulty: "Easy",
    rating: 4.7,
    playable: true,
    color: "var(--neon-cyan)",
    icon: "🏢",
    accent: "#00f0ff"
  },
  {
    id: "reflex-racer",
    title: "Reflex Racer",
    category: "Action",
    description: "Speed down a neon-drenched highway. Tap left/right or arrow keys to switch lanes and dodge high-speed traffic!",
    mechanics: "Lane-changing and dodging oncoming vehicles.",
    difficulty: "Hard",
    rating: 4.9,
    playable: true,
    color: "var(--neon-lime)",
    icon: "🏎️",
    accent: "#39ff14"
  },
  {
    id: "endless-runner",
    title: "Space Runner 3D",
    category: "Action",
    description: "Dash and slide through a futuristic city. Collect power-ups and dodge obstacles in this fast-paced endless test of reflexes.",
    mechanics: "Swipe and dodge in 3 lanes.",
    difficulty: "Hard",
    rating: 4.6,
    playable: false,
    color: "var(--neon-purple)",
    icon: "🏃",
    accent: "#b026ff"
  },
  {
    id: "merge-puzzle",
    title: "Cosmic Merge",
    category: "Puzzle",
    description: "Combine matching orbital elements to synthesize higher-tier gems and elements. Can you create the ultimate crystal?",
    mechanics: "Drag, match, and combine.",
    difficulty: "Medium",
    rating: 4.5,
    playable: false,
    color: "var(--neon-yellow)",
    icon: "💎",
    accent: "#ffea00"
  },
  {
    id: "idle-miner",
    title: "Neon Idle Miner",
    category: "Casual",
    description: "Manage a futuristic mineral mine. Purchase automated lasers, upgrade drill heads, and prestige to colonize other planets.",
    mechanics: "Clicker, incremental progress.",
    difficulty: "Easy",
    rating: 4.4,
    playable: false,
    color: "var(--neon-cyan)",
    icon: "⛏️",
    accent: "#00f0ff"
  },
  {
    id: "match-3-candy",
    title: "Retro Candy Match",
    category: "Puzzle",
    description: "Swap and match 3 or more neon candies to clear the grid. Set off dazzling chain reactions and unlock special boosters.",
    mechanics: "Grid matching and swap mechanics.",
    difficulty: "Medium",
    rating: 4.7,
    playable: false,
    color: "var(--neon-pink)",
    icon: "🍬",
    accent: "#ff007f"
  },
  {
    id: "bubble-shooter",
    title: "Bubble Pulse",
    category: "Arcade",
    description: "Aim, match, and pop vibrant spheres in this classic match-3 shooter with realistic bouncing physics and unique puzzles.",
    mechanics: "Aiming and physics-based shooting.",
    difficulty: "Medium",
    rating: 4.6,
    playable: false,
    color: "var(--neon-lime)",
    icon: "🔮",
    accent: "#39ff14"
  },
  {
    id: "space-defender",
    title: "Galactic Defender",
    category: "Action",
    description: "Pilot your defensive ship and repel waves of retro-styled invaders and giant screen-filling boss encounters.",
    mechanics: "Horizontal movement and continuous shooting.",
    difficulty: "Hard",
    rating: 4.8,
    playable: false,
    color: "var(--neon-pink)",
    icon: "🛸",
    accent: "#ff007f"
  },
  {
    id: "word-search",
    title: "Neon Word Sleuth",
    category: "Puzzle",
    description: "Find the hidden words in a glowing letter matrix. Test your vocabulary against the ticking clock in themed puzzles.",
    mechanics: "Grid swipe selection of words.",
    difficulty: "Easy",
    rating: 4.3,
    playable: false,
    color: "var(--neon-yellow)",
    icon: "🔍",
    accent: "#ffea00"
  },
  {
    id: "math-mahjong",
    title: "Math Mahjong Pulse",
    category: "Puzzle",
    description: "Match traditional tiles whose values sum up to the targets. Combine speed math with classic mahjong strategy.",
    mechanics: "Match sums to clear matching tiles.",
    difficulty: "Medium",
    rating: 4.2,
    playable: false,
    color: "var(--neon-purple)",
    icon: "🀄",
    accent: "#b026ff"
  },
  {
    id: "air-hockey",
    title: "Air Hockey Battle",
    category: "Arcade",
    description: "Experience fast, physics-based action in local single-player against advanced AI or with a friend on the same screen.",
    mechanics: "Touch or mouse paddle control.",
    difficulty: "Medium",
    rating: 4.5,
    playable: false,
    color: "var(--neon-cyan)",
    icon: "🏒",
    accent: "#00f0ff"
  },
  {
    id: "archery-master",
    title: "Precision Archery",
    category: "Casual",
    description: "Draw your bow, factor in shifting wind speeds, and release to hit moving bullseyes in beautiful geometric environments.",
    mechanics: "Drag to pull back, aim, and release.",
    difficulty: "Medium",
    rating: 4.6,
    playable: false,
    color: "var(--neon-lime)",
    icon: "🏹",
    accent: "#39ff14"
  },
  {
    id: "sushi-spin",
    title: "Sushi Spin Master",
    category: "Casual",
    description: "Drop delicious sushi layers on rotating conveyor plates. Stack them as high as possible without causing a delicious mess.",
    mechanics: "Tap to drop on a spinning disk.",
    difficulty: "Easy",
    rating: 4.4,
    playable: false,
    color: "var(--neon-pink)",
    icon: "🍣",
    accent: "#ff007f"
  },
  {
    id: "platform-jumper",
    title: "Cyber Neon Jump",
    category: "Action",
    description: "Scale a dynamic network of platforms, avoiding traps, lasers, and enemies. How high can you climb?",
    mechanics: "Jump-and-run side-scroller layout.",
    difficulty: "Hard",
    rating: 4.7,
    playable: false,
    color: "var(--neon-purple)",
    icon: "🧗",
    accent: "#b026ff"
  },
  {
    id: "balloon-pop",
    title: "Balloon Burst Mania",
    category: "Casual",
    description: "Tap groups of ascending helium balloons before they drift off screen. Chain together massive pop combos and score multipliers.",
    mechanics: "Rapid tapping and combo grouping.",
    difficulty: "Easy",
    rating: 4.3,
    playable: false,
    color: "var(--neon-yellow)",
    icon: "🎈",
    accent: "#ffea00"
  },
  {
    id: "pixel-painter",
    title: "Neon Pixel Painter",
    category: "Casual",
    description: "Immerse yourself in relaxing canvas coloring. Draw by numbers to unlock beautifully glowing vector and pixel artwork.",
    mechanics: "Color picker and grid filling.",
    difficulty: "Easy",
    rating: 4.5,
    playable: false,
    color: "var(--neon-cyan)",
    icon: "🎨",
    accent: "#00f0ff"
  },
  {
    id: "merge-restaurant",
    title: "Merge & Diner",
    category: "Puzzle",
    description: "Merge raw food ingredients to prepare gourmet dishes and complete fast-paced customer orders in your neon diner.",
    mechanics: "Grid merging and recipe progression.",
    difficulty: "Medium",
    rating: 4.6,
    playable: false,
    color: "var(--neon-lime)",
    icon: "🍳",
    accent: "#39ff14"
  },
  {
    id: "road-traffic",
    title: "Neon Traffic Dodger",
    category: "Action",
    description: "Guide a lost retro pixel character across multi-lane highways teeming with high-speed futuristic hovercars.",
    mechanics: "Tap/swipe to step through lanes.",
    difficulty: "Medium",
    rating: 4.4,
    playable: false,
    color: "var(--neon-purple)",
    icon: "🚶",
    accent: "#b026ff"
  },
  {
    id: "retro-snake",
    title: "Cyber Snake Retro",
    category: "Arcade",
    description: "Control a growing electric snake to consume glowing data packets while avoiding self-collision and screen edges.",
    mechanics: "Directional arrow controls and boundary dodging.",
    difficulty: "Easy",
    rating: 4.6,
    playable: true,
    color: "var(--neon-cyan)",
    icon: "🐍",
    accent: "#00f0ff"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = gamesData;
}
